### ISSUE TITLE
Need to be able to edit the name of a playlist

### ISSUE THREAD

**Issue by dlanghorne0428** [dlanghorne0428/StudioMusicPlayer#31]
Currently no way to change it, except for the admin change.

**Comment by sagarsadhu** [comment]
Hi @dlanghorne0428 , I am interested in working on this issue.

**Comment by dlanghorne0428** [comment]
Hello @sagarsadhu, thanks for the interest - however this is just a learning project that I was working on with my daughter. If I need some help in the future, I will reach out.

**Comment by dlanghorne0428** [comment]
Closed with pull request #44
